---
title: "repr_revisions.Rmd"
author: "Braden T Tierney"
date: "11/13/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(ComplexUpset)
```

```{r}
setwd('~/Dropbox (Mason Lab)/repr_revisions/')

clr_3var = readRDS('clr_3var_voe.rds')
clr_3var[[4]] = clr_3var[[4]][names(clr_3var[[4]])!='initial_association_output']
clr_6var = readRDS('clr_6var_voe.rds')
clr_6var[[4]] = clr_6var[[4]][names(clr_6var[[4]])!='initial_association_output']
clr_9var = readRDS('clr_9var_voe.rds')
clr_9var[[4]] = clr_9var[[4]][names(clr_9var[[4]])!='initial_association_output']

logged_3var = readRDS('logged_3var_voe.rds')
logged_3var[[4]] = logged_3var[[4]][names(logged_3var[[4]])!='initial_association_output']
logged_6var = readRDS('logged_6var_voe.rds')
logged_6var[[4]] = logged_6var[[4]][names(logged_6var[[4]])!='initial_association_output']
logged_9var = readRDS('logged_9var_voe.rds')
logged_9var[[4]] = logged_9var[[4]][names(logged_9var[[4]])!='initial_association_output']

nonlogged_3var = readRDS('nonlogged_3var_voe.rds')
nonlogged_3var[[4]] = nonlogged_3var[[4]][names(nonlogged_3var[[4]])!='initial_association_output']
nonlogged_6var = readRDS('nonlogged_6var_voe.rds')
nonlogged_6var[[4]] = nonlogged_6var[[4]][names(nonlogged_6var[[4]])!='initial_association_output']
nonlogged_9var = readRDS('nonlogged_9var_voe.rds')
nonlogged_9var[[4]] = nonlogged_9var[[4]][names(nonlogged_9var[[4]])!='initial_association_output']
```

```{r}
### doing one upset R plot for number of variables included in model

### upsetr plots showing initially fdr significant

# all baseline associations

clr_3var_processed = map(clr_3var, function(x) x[[2]] %>% mutate(significant_initial = if_else(BY<=0.05,1,0)) %>% select(feature,significant_initial)) %>% reduce(inner_join,by='feature')
colnames(clr_3var_processed) = c('feature','clr_dataset_1','clr_dataset_2','clr_dataset_3','clr_meta_analysis')

logged_3var_processed = map(logged_3var, function(x) x[[2]] %>% mutate(significant_initial = if_else(BY<=0.05,1,0)) %>% select(feature,significant_initial)) %>% reduce(inner_join,by='feature')
colnames(logged_3var_processed) = c('feature','logged_dataset_1','logged_dataset_2','logged_dataset_3','logged_meta_analysis')

nonlogged_3var_processed = map(nonlogged_3var, function(x) x[[2]] %>% mutate(significant_initial = if_else(BY<=0.05,1,0)) %>% select(feature,significant_initial)) %>% reduce(inner_join,by='feature')
colnames(nonlogged_3var_processed) = c('feature','nonlogged_dataset_1','nonlogged_dataset_2','nonlogged_dataset_3','nonlogged_meta_analysis')

var3_all = full_join(clr_3var_processed,logged_3var_processed,by='feature')
var3_all = full_join(var3_all,nonlogged_3var_processed,by='feature') %>% select(-feature)
var3_all[is.na(var3_all)] = 0

upset(var3_all %>% as.data.frame,colnames(var3_all),keep_empty_groups=TRUE)

### pval sig at least once plots

# 3 var
clr_3var_processed = map(clr_3var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(clr_3var_processed) = c('feature','clr_3var_dataset_1','clr_3var_dataset_2','clr_3var_dataset_3','clr_3var_meta_analysis')

logged_3var_processed = map(logged_3var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(logged_3var_processed) = c('feature','logged_3var_dataset_1','logged_3var_dataset_2','logged_3var_dataset_3','logged_3var_meta_analysis')
colnames(logged_3var_processed) = c('feature','logged_3var_dataset_1','logged_3var_dataset_2','logged_3var_dataset_3','logged_3var_meta_analysis')

nonlogged_3var_processed = map(nonlogged_3var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_3var_processed) = c('feature','nonlogged_3var_dataset_1','nonlogged_3var_dataset_2','nonlogged_3var_dataset_3','nonlogged_3var_meta_analysis')

var3_all = full_join(clr_3var_processed,logged_3var_processed,by='feature')
var3_all = full_join(var3_all,nonlogged_3var_processed,by='feature') %>% select(-feature)
var3_all[is.na(var3_all)] = 0

upset(var3_all %>% as.data.frame,colnames(var3_all),keep_empty_groups=TRUE, sort_sets=FALSE)

# 6 var
clr_6var_processed = map(clr_6var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(clr_6var_processed) = c('feature','clr_6var_dataset_1','clr_6var_dataset_2','clr_6var_dataset_3','clr_6var_meta_analysis')

logged_6var_processed = map(logged_6var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(logged_6var_processed) = c('feature','logged_6var_dataset_1','logged_6var_dataset_2','logged_6var_dataset_3','logged_6var_meta_analysis')
colnames(logged_6var_processed) = c('feature','logged_6var_dataset_1','logged_6var_dataset_2','logged_6var_dataset_3','logged_6var_meta_analysis')

nonlogged_6var_processed = map(nonlogged_6var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_6var_processed) = c('feature','nonlogged_6var_dataset_1','nonlogged_6var_dataset_2','nonlogged_6var_dataset_3','nonlogged_6var_meta_analysis')

var6_all = full_join(clr_6var_processed,logged_6var_processed,by='feature')
var6_all = full_join(var6_all,nonlogged_6var_processed,by='feature') %>% select(-feature)
var6_all[is.na(var6_all)] = 0

upset(var6_all %>% as.data.frame,colnames(var6_all),keep_empty_groups=TRUE, sort_sets=FALSE)

# 9 var
clr_9var_processed = map(clr_9var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(clr_9var_processed) = c('feature','clr_9var_dataset_1','clr_9var_dataset_2','clr_9var_dataset_3','clr_9var_meta_analysis')

logged_9var_processed = map(logged_9var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(logged_9var_processed) = c('feature','logged_9var_dataset_1','logged_9var_dataset_2','logged_9var_dataset_3','logged_9var_meta_analysis')
colnames(logged_9var_processed) = c('feature','logged_9var_dataset_1','logged_9var_dataset_2','logged_9var_dataset_3','logged_9var_meta_analysis')

nonlogged_9var_processed = map(nonlogged_9var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<0.05,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_9var_processed) = c('feature','nonlogged_9var_dataset_1','nonlogged_9var_dataset_2','nonlogged_9var_dataset_3','nonlogged_9var_meta_analysis')

var9_all = full_join(clr_9var_processed,logged_9var_processed,by='feature')
var9_all = full_join(var9_all,nonlogged_9var_processed,by='feature') %>% select(-feature)
var9_all[is.na(var9_all)] = 0

upset(var9_all %>% as.data.frame,colnames(var9_all),keep_empty_groups=TRUE, sort_sets=FALSE)

### fdr sig at least once plots

# 3 var
bonf_equivalent = 0.05/535
clr_3var_processed = map(clr_3var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(clr_3var_processed) = c('feature','clr_3var_dataset_1','clr_3var_dataset_2','clr_3var_dataset_3','clr_3var_meta_analysis')

logged_3var_processed = map(logged_3var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(logged_3var_processed) = c('feature','logged_3var_dataset_1','logged_3var_dataset_2','logged_3var_dataset_3','logged_3var_meta_analysis')
colnames(logged_3var_processed) = c('feature','logged_3var_dataset_1','logged_3var_dataset_2','logged_3var_dataset_3','logged_3var_meta_analysis')

nonlogged_3var_processed = map(nonlogged_3var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_3var_processed) = c('feature','nonlogged_3var_dataset_1','nonlogged_3var_dataset_2','nonlogged_3var_dataset_3','nonlogged_3var_meta_analysis')

var3_all = full_join(clr_3var_processed,logged_3var_processed,by='feature')
var3_all = full_join(var3_all,nonlogged_3var_processed,by='feature') %>% select(-feature)
var3_all[is.na(var3_all)] = 0

upset(var3_all %>% as.data.frame,colnames(var3_all),keep_empty_groups=TRUE, sort_sets=FALSE)

# 6 var
clr_6var_processed = map(clr_6var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(clr_6var_processed) = c('feature','clr_6var_dataset_1','clr_6var_dataset_2','clr_6var_dataset_3','clr_6var_meta_analysis')

logged_6var_processed = map(logged_6var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(logged_6var_processed) = c('feature','logged_6var_dataset_1','logged_6var_dataset_2','logged_6var_dataset_3','logged_6var_meta_analysis')
colnames(logged_6var_processed) = c('feature','logged_6var_dataset_1','logged_6var_dataset_2','logged_6var_dataset_3','logged_6var_meta_analysis')

nonlogged_6var_processed = map(nonlogged_6var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_6var_processed) = c('feature','nonlogged_6var_dataset_1','nonlogged_6var_dataset_2','nonlogged_6var_dataset_3','nonlogged_6var_meta_analysis')

var6_all = full_join(clr_6var_processed,logged_6var_processed,by='feature')
var6_all = full_join(var6_all,nonlogged_6var_processed,by='feature') %>% select(-feature)
var6_all[is.na(var6_all)] = 0

upset(var6_all %>% as.data.frame,colnames(var6_all),keep_empty_groups=TRUE, sort_sets=FALSE)

# 9 var
clr_9var_processed = map(clr_9var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(clr_9var_processed) = c('feature','clr_9var_dataset_1','clr_9var_dataset_2','clr_9var_dataset_3','clr_9var_meta_analysis')

logged_9var_processed = map(logged_9var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(logged_9var_processed) = c('feature','logged_9var_dataset_1','logged_9var_dataset_2','logged_9var_dataset_3','logged_9var_meta_analysis')
colnames(logged_9var_processed) = c('feature','logged_9var_dataset_1','logged_9var_dataset_2','logged_9var_dataset_3','logged_9var_meta_analysis')

nonlogged_9var_processed = map(nonlogged_9var, function(x) x[[5]][[3]]  %>% mutate(pval_sig = if_else(p.value<bonf_equivalent,1,0)) %>% select(dependent_feature,pval_sig) %>%  group_by(dependent_feature) %>% summarize(pval_sig_once = sum(pval_sig)) %>% mutate(pval_sig_once = if_else(pval_sig_once == 0, 0, 1))) %>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_9var_processed) = c('feature','nonlogged_9var_dataset_1','nonlogged_9var_dataset_2','nonlogged_9var_dataset_3','nonlogged_9var_meta_analysis')

var9_all = full_join(clr_9var_processed,logged_9var_processed,by='feature')
var9_all = full_join(var9_all,nonlogged_9var_processed,by='feature') %>% select(-feature)
var9_all[is.na(var9_all)] = 0

upset(var9_all %>% as.data.frame,colnames(var9_all),keep_empty_groups=TRUE, sort_sets=FALSE)

```


```{r}
# correlation between janus effects, one per number of variables included in the model

# 3 var
clr_3var_processed = map(clr_3var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(clr_3var_processed) = c('feature','clr_3var_dataset_1','clr_3var_dataset_2','clr_3var_dataset_3')

logged_3var_processed = map(logged_3var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(logged_3var_processed) = c('feature','logged_3var_dataset_1','logged_3var_dataset_2','logged_3var_dataset_3')

nonlogged_3var_processed = map(nonlogged_3var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_3var_processed) = c('feature','nonlogged_3var_dataset_1','nonlogged_3var_dataset_2','nonlogged_3var_dataset_3')

var3_all = full_join(clr_3var_processed,logged_3var_processed,by='feature')
var3_all = full_join(var3_all,nonlogged_3var_processed,by='feature')
var3_all[is.na(var3_all)] = 0

# 6 var 
clr_6var_processed = map(clr_6var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(clr_6var_processed) = c('feature','clr_6var_dataset_1','clr_6var_dataset_2','clr_6var_dataset_3')

logged_6var_processed = map(logged_6var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(logged_6var_processed) = c('feature','logged_6var_dataset_1','logged_6var_dataset_2','logged_6var_dataset_3')

nonlogged_6var_processed = map(nonlogged_6var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_6var_processed) = c('feature','nonlogged_6var_dataset_1','nonlogged_6var_dataset_2','nonlogged_6var_dataset_3')

var6_all = full_join(clr_6var_processed,logged_6var_processed,by='feature')
var6_all = full_join(var6_all,nonlogged_6var_processed,by='feature')
var6_all[is.na(var6_all)] = 0

# 9 var
clr_9var_processed = map(clr_9var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(clr_9var_processed) = c('feature','clr_9var_dataset_1','clr_9var_dataset_2','clr_9var_dataset_3')

logged_9var_processed = map(logged_9var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(logged_9var_processed) = c('feature','logged_9var_dataset_1','logged_9var_dataset_2','logged_9var_dataset_3')

nonlogged_9var_processed = map(nonlogged_9var[1:3], function(x) x[[5]][[1]] %>% select(dependent_feature,janus_effect))%>% reduce(inner_join,by='dependent_feature')
colnames(nonlogged_9var_processed) = c('feature','nonlogged_9var_dataset_1','nonlogged_9var_dataset_2','nonlogged_9var_dataset_3')

var9_all = full_join(clr_9var_processed,logged_9var_processed,by='feature')
var9_all = full_join(var9_all,nonlogged_9var_processed,by='feature')
var9_all[is.na(var9_all)] = 0

var_all = full_join(var3_all,var6_all,by='feature')
var_all = full_join(var_all,var9_all,by='feature') %>% select(-feature)

save_pheatmap_pdf <- function(x, filename, width=7, height=7) {
   stopifnot(!missing(x))
   stopifnot(!missing(filename))
   pdf(filename, width=width, height=height)
   grid::grid.newpage()
   grid::grid.draw(x$gtable)
   dev.off()
}

outmap = var_all %>% cor %>% pheatmap
save_pheatmap_pdf(outmap, '~/Dropbox (Mason Lab)/repr_revisions/janus_heatmap.pdf')

```

```{r}
# deal with the number of vibrations subsampling point 

setwd('~/Dropbox (Mason Lab)/repr_revisions/')

subsample = readRDS('vibration_subsampling_analysis.rds')

```

